/* Auto-generated by scripts/extract-all-industries.js — do not edit */
import type { IndustryPageContent } from "@/lib/industries/types";

import toy_action_figure from "@/lib/industries/content/toy/action-figure.json";
import toy_category from "@/lib/industries/content/toy/category.json";
import toy_custom_molded from "@/lib/industries/content/toy/custom-molded.json";
import toy_packaging_trays from "@/lib/industries/content/toy/packaging-trays.json";
import toy_protective from "@/lib/industries/content/toy/protective.json";
import toy_retail_display from "@/lib/industries/content/toy/retail-display.json";
import toy_set_inserts from "@/lib/industries/content/toy/set-inserts.json";
import electronics_category from "@/lib/industries/content/electronics/category.json";
import electronics_connector from "@/lib/industries/content/electronics/connector.json";
import electronics_consumer from "@/lib/industries/content/electronics/consumer.json";
import electronics_esd from "@/lib/industries/content/electronics/esd.json";
import electronics_pcb from "@/lib/industries/content/electronics/pcb.json";
import electronics_switches from "@/lib/industries/content/electronics/switches.json";
import fmcg_bakery from "@/lib/industries/content/fmcg/bakery.json";
import fmcg_category from "@/lib/industries/content/fmcg/category.json";
import fmcg_custom from "@/lib/industries/content/fmcg/custom.json";
import fmcg_food_bev from "@/lib/industries/content/fmcg/food-bev.json";
import fmcg_retail from "@/lib/industries/content/fmcg/retail.json";
import industrial_category from "@/lib/industries/content/industrial/category.json";
import industrial_enclosures from "@/lib/industries/content/industrial/enclosures.json";
import industrial_machinery from "@/lib/industries/content/industrial/machinery.json";
import industrial_power_tools from "@/lib/industries/content/industrial/power-tools.json";
import medical_cardiology from "@/lib/industries/content/medical/cardiology.json";
import medical_category from "@/lib/industries/content/medical/category.json";
import medical_drug_delivery from "@/lib/industries/content/medical/drug-delivery.json";
import medical_oncology from "@/lib/industries/content/medical/oncology.json";
import medical_ophthalmic from "@/lib/industries/content/medical/ophthalmic.json";
import medical_ortho from "@/lib/industries/content/medical/ortho.json";
import medical_respiratory from "@/lib/industries/content/medical/respiratory.json";
import medical_vascular from "@/lib/industries/content/medical/vascular.json";
import medical_wound_care from "@/lib/industries/content/medical/wound-care.json";
import pharmaceutical_ampoule from "@/lib/industries/content/pharmaceutical/ampoule.json";
import pharmaceutical_category from "@/lib/industries/content/pharmaceutical/category.json";
import pharmaceutical_child_resistant from "@/lib/industries/content/pharmaceutical/child-resistant.json";
import pharmaceutical_diagnostic from "@/lib/industries/content/pharmaceutical/diagnostic.json";
import pharmaceutical_sample_kit from "@/lib/industries/content/pharmaceutical/sample-kit.json";
import pharmaceutical_sterile from "@/lib/industries/content/pharmaceutical/sterile.json";
import pharmaceutical_strip from "@/lib/industries/content/pharmaceutical/strip.json";
import pharmaceutical_syringe from "@/lib/industries/content/pharmaceutical/syringe.json";
import pharmaceutical_tamper_proof from "@/lib/industries/content/pharmaceutical/tamper-proof.json";
import stationery_category from "@/lib/industries/content/stationery/category.json";
import stationery_display from "@/lib/industries/content/stationery/display.json";
import stationery_eraser from "@/lib/industries/content/stationery/eraser.json";
import stationery_gift_set from "@/lib/industries/content/stationery/gift-set.json";
import stationery_office from "@/lib/industries/content/stationery/office.json";
import stationery_pen_marker from "@/lib/industries/content/stationery/pen-marker.json";
import stationery_school_kit from "@/lib/industries/content/stationery/school-kit.json";
import manufacturing_blister_packaging from "@/lib/industries/content/manufacturing/blister-packaging.json";
import manufacturing_category from "@/lib/industries/content/manufacturing/category.json";
import manufacturing_clamshell_packaging from "@/lib/industries/content/manufacturing/clamshell-packaging.json";
import manufacturing_materials from "@/lib/industries/content/manufacturing/materials.json";
import manufacturing_plastic_packaging from "@/lib/industries/content/manufacturing/plastic-packaging.json";
import manufacturing_pressure_forming from "@/lib/industries/content/manufacturing/pressure-forming.json";
import manufacturing_thermoforming_packaging from "@/lib/industries/content/manufacturing/thermoforming-packaging.json";
import manufacturing_vacuum_forming from "@/lib/industries/content/manufacturing/vacuum-forming.json";
import expertise_cleanroom from "@/lib/industries/content/expertise/cleanroom.json";
import expertise_contract_manufacturing from "@/lib/industries/content/expertise/contract-manufacturing.json";
import expertise_hub from "@/lib/industries/content/expertise/hub.json";
import expertise_rnd_innovation from "@/lib/industries/content/expertise/rnd-innovation.json";
import expertise_unique_offer from "@/lib/industries/content/expertise/unique-offer.json";

import automobile_assembly_line_trays from "@/lib/industries/content/automobile/assembly-line-trays.json";
import automobile_category from "@/lib/industries/content/automobile/category.json";
import automobile_exterior_component_packaging from "@/lib/industries/content/automobile/exterior-component-packaging.json";
import automobile_interior_fittings_packaging from "@/lib/industries/content/automobile/interior-fittings-packaging.json";
import automobile_mechanical_parts_packaging from "@/lib/industries/content/automobile/mechanical-parts-packaging.json";
import automobile_sensor_electrical_packaging from "@/lib/industries/content/automobile/sensor-electrical-packaging.json";

import cosmetics_category from "@/lib/industries/content/cosmetics/category.json";
import cosmetics_cosmetic_beauty_packaging from "@/lib/industries/content/cosmetics/cosmetic-beauty-packaging.json";
import cosmetics_gift_set_display_trays from "@/lib/industries/content/cosmetics/gift-set-display-trays.json";
import cosmetics_lipstick_compact_case_inserts from "@/lib/industries/content/cosmetics/lipstick-compact-case-inserts.json";
import cosmetics_makeup_kit_thermoformed_trays from "@/lib/industries/content/cosmetics/makeup-kit-thermoformed-trays.json";
import cosmetics_perfume_bottle_insert_trays from "@/lib/industries/content/cosmetics/perfume-bottle-insert-trays.json";
import cosmetics_transparent_thermoformed_cosmetic_packaging from "@/lib/industries/content/cosmetics/transparent-thermoformed-cosmetic-packaging.json";

import baby_care_baby_accessories_trays from "@/lib/industries/content/baby-care/baby-accessories-trays.json";
import baby_care_baby_product_packaging from "@/lib/industries/content/baby-care/baby-product-packaging.json";
import baby_care_baby_toy_packaging from "@/lib/industries/content/baby-care/baby-toy-packaging.json";
import baby_care_category from "@/lib/industries/content/baby-care/category.json";
import baby_care_feeding_bottle_packaging from "@/lib/industries/content/baby-care/feeding-bottle-packaging.json";
import baby_care_hygiene_product_trays from "@/lib/industries/content/baby-care/hygiene-product-trays.json";
import baby_care_lotion_cream_tray_inserts from "@/lib/industries/content/baby-care/lotion-cream-tray-inserts.json";

export const industryContentMap: Record<
  string,
  Record<string, IndustryPageContent>
> = {
  toy: {
    "action-figure": toy_action_figure as IndustryPageContent,
    "category": toy_category as IndustryPageContent,
    "custom-molded": toy_custom_molded as IndustryPageContent,
    "packaging-trays": toy_packaging_trays as IndustryPageContent,
    "protective": toy_protective as IndustryPageContent,
    "retail-display": toy_retail_display as IndustryPageContent,
    "set-inserts": toy_set_inserts as IndustryPageContent
  },
  electronics: {
    "category": electronics_category as IndustryPageContent,
    "connector": electronics_connector as IndustryPageContent,
    "consumer": electronics_consumer as IndustryPageContent,
    "esd": electronics_esd as IndustryPageContent,
    "pcb": electronics_pcb as IndustryPageContent,
    "switches": electronics_switches as IndustryPageContent
  },
  fmcg: {
    "bakery": fmcg_bakery as IndustryPageContent,
    "category": fmcg_category as IndustryPageContent,
    "custom": fmcg_custom as IndustryPageContent,
    "food-bev": fmcg_food_bev as IndustryPageContent,
    "retail": fmcg_retail as IndustryPageContent
  },
  industrial: {
    "category": industrial_category as IndustryPageContent,
    "enclosures": industrial_enclosures as IndustryPageContent,
    "machinery": industrial_machinery as IndustryPageContent,
    "power-tools": industrial_power_tools as IndustryPageContent
  },
  medical: {
    "cardiology": medical_cardiology as IndustryPageContent,
    "category": medical_category as IndustryPageContent,
    "drug-delivery": medical_drug_delivery as IndustryPageContent,
    "oncology": medical_oncology as IndustryPageContent,
    "ophthalmic": medical_ophthalmic as IndustryPageContent,
    "ortho": medical_ortho as IndustryPageContent,
    "respiratory": medical_respiratory as IndustryPageContent,
    "vascular": medical_vascular as IndustryPageContent,
    "wound-care": medical_wound_care as IndustryPageContent
  },
  pharmaceutical: {
    "ampoule": pharmaceutical_ampoule as IndustryPageContent,
    "category": pharmaceutical_category as IndustryPageContent,
    "child-resistant": pharmaceutical_child_resistant as IndustryPageContent,
    "diagnostic": pharmaceutical_diagnostic as IndustryPageContent,
    "sample-kit": pharmaceutical_sample_kit as IndustryPageContent,
    "sterile": pharmaceutical_sterile as IndustryPageContent,
    "strip": pharmaceutical_strip as IndustryPageContent,
    "syringe": pharmaceutical_syringe as IndustryPageContent,
    "tamper-proof": pharmaceutical_tamper_proof as IndustryPageContent
  },
  stationery: {
    "category": stationery_category as IndustryPageContent,
    "display": stationery_display as IndustryPageContent,
    "eraser": stationery_eraser as IndustryPageContent,
    "gift-set": stationery_gift_set as IndustryPageContent,
    "office": stationery_office as IndustryPageContent,
    "pen-marker": stationery_pen_marker as IndustryPageContent,
    "school-kit": stationery_school_kit as IndustryPageContent
  },
  manufacturing: {
    "category": manufacturing_category as IndustryPageContent,
    "blister-packaging": manufacturing_blister_packaging as IndustryPageContent,
    "clamshell-packaging": manufacturing_clamshell_packaging as IndustryPageContent,
    "materials": manufacturing_materials as IndustryPageContent,
    "plastic-packaging": manufacturing_plastic_packaging as IndustryPageContent,
    "pressure-forming": manufacturing_pressure_forming as IndustryPageContent,
    "thermoforming-packaging": manufacturing_thermoforming_packaging as IndustryPageContent,
    "vacuum-forming": manufacturing_vacuum_forming as IndustryPageContent
  },
  expertise: {
    "cleanroom": expertise_cleanroom as IndustryPageContent,
    "contract-manufacturing": expertise_contract_manufacturing as IndustryPageContent,
    "hub": expertise_hub as IndustryPageContent,
    "rnd-innovation": expertise_rnd_innovation as IndustryPageContent,
    "unique-offer": expertise_unique_offer as IndustryPageContent
  },
  automobile: {
    "assembly-line-trays": automobile_assembly_line_trays as IndustryPageContent,
    "category": automobile_category as IndustryPageContent,
    "exterior-component-packaging": automobile_exterior_component_packaging as IndustryPageContent,
    "interior-fittings-packaging": automobile_interior_fittings_packaging as IndustryPageContent,
    "mechanical-parts-packaging": automobile_mechanical_parts_packaging as IndustryPageContent,
    "sensor-electrical-packaging": automobile_sensor_electrical_packaging as IndustryPageContent
  },
  "cosmetics": {
    "category": cosmetics_category as IndustryPageContent,
    "cosmetic-beauty-packaging": cosmetics_cosmetic_beauty_packaging as IndustryPageContent,
    "gift-set-display-trays": cosmetics_gift_set_display_trays as IndustryPageContent,
    "lipstick-compact-case-inserts": cosmetics_lipstick_compact_case_inserts as IndustryPageContent,
    "makeup-kit-thermoformed-trays": cosmetics_makeup_kit_thermoformed_trays as IndustryPageContent,
    "perfume-bottle-insert-trays": cosmetics_perfume_bottle_insert_trays as IndustryPageContent,
    "transparent-thermoformed-cosmetic-packaging": cosmetics_transparent_thermoformed_cosmetic_packaging as IndustryPageContent
  },
  "baby-care": {
    "baby-accessories-trays": baby_care_baby_accessories_trays as IndustryPageContent,
    "baby-product-packaging": baby_care_baby_product_packaging as IndustryPageContent,
    "baby-toy-packaging": baby_care_baby_toy_packaging as IndustryPageContent,
    "category": baby_care_category as IndustryPageContent,
    "feeding-bottle-packaging": baby_care_feeding_bottle_packaging as IndustryPageContent,
    "hygiene-product-trays": baby_care_hygiene_product_trays as IndustryPageContent,
    "lotion-cream-tray-inserts": baby_care_lotion_cream_tray_inserts as IndustryPageContent
  }
};